/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

export * from './collectFeesFromCpAmmEvent';
export * from './initializeAmmsConfigEvent';
export * from './initializeAmmsConfigsManagerEvent';
export * from './initializeCpAmmEvent';
export * from './launchCpAmmEvent';
export * from './provideToCpAmmEvent';
export * from './q64128';
export * from './swapInCpAmmEvent';
export * from './u192';
export * from './updateAmmsConfigFeeAuthorityEvent';
export * from './updateAmmsConfigProtocolFeeRateEvent';
export * from './updateAmmsConfigProvidersFeeRateEvent';
export * from './updateAmmsConfigsManagerAuthorityEvent';
export * from './updateAmmsConfigsManagerHeadAuthorityEvent';
export * from './withdrawFromCpAmmEvent';
