/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type InitializeAmmsConfigEvent = {
  authority: Address;
  ammsConfig: Address;
  feeAuthority: Address;
  protocolFeeRateBasisPoints: number;
  providersFeeRateBasisPoints: number;
  id: bigint;
  timestamp: bigint;
};

export type InitializeAmmsConfigEventArgs = {
  authority: Address;
  ammsConfig: Address;
  feeAuthority: Address;
  protocolFeeRateBasisPoints: number;
  providersFeeRateBasisPoints: number;
  id: number | bigint;
  timestamp: number | bigint;
};

export function getInitializeAmmsConfigEventEncoder(): Encoder<InitializeAmmsConfigEventArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['ammsConfig', getAddressEncoder()],
    ['feeAuthority', getAddressEncoder()],
    ['protocolFeeRateBasisPoints', getU16Encoder()],
    ['providersFeeRateBasisPoints', getU16Encoder()],
    ['id', getU64Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getInitializeAmmsConfigEventDecoder(): Decoder<InitializeAmmsConfigEvent> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['ammsConfig', getAddressDecoder()],
    ['feeAuthority', getAddressDecoder()],
    ['protocolFeeRateBasisPoints', getU16Decoder()],
    ['providersFeeRateBasisPoints', getU16Decoder()],
    ['id', getU64Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getInitializeAmmsConfigEventCodec(): Codec<
  InitializeAmmsConfigEventArgs,
  InitializeAmmsConfigEvent
> {
  return combineCodec(
    getInitializeAmmsConfigEventEncoder(),
    getInitializeAmmsConfigEventDecoder()
  );
}
