/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type InitializeAmmsConfigsManagerEvent = {
  signer: Address;
  authority: Address;
  headAuthority: Address;
  timestamp: bigint;
};

export type InitializeAmmsConfigsManagerEventArgs = {
  signer: Address;
  authority: Address;
  headAuthority: Address;
  timestamp: number | bigint;
};

export function getInitializeAmmsConfigsManagerEventEncoder(): Encoder<InitializeAmmsConfigsManagerEventArgs> {
  return getStructEncoder([
    ['signer', getAddressEncoder()],
    ['authority', getAddressEncoder()],
    ['headAuthority', getAddressEncoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getInitializeAmmsConfigsManagerEventDecoder(): Decoder<InitializeAmmsConfigsManagerEvent> {
  return getStructDecoder([
    ['signer', getAddressDecoder()],
    ['authority', getAddressDecoder()],
    ['headAuthority', getAddressDecoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getInitializeAmmsConfigsManagerEventCodec(): Codec<
  InitializeAmmsConfigsManagerEventArgs,
  InitializeAmmsConfigsManagerEvent
> {
  return combineCodec(
    getInitializeAmmsConfigsManagerEventEncoder(),
    getInitializeAmmsConfigsManagerEventDecoder()
  );
}
