/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type LiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEvent =
  { authority: Address; newAuthority: Address; timestamp: bigint };

export type LiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEventArgs =
  { authority: Address; newAuthority: Address; timestamp: number | bigint };

export function getLiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEventEncoder(): Encoder<LiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEventArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['newAuthority', getAddressEncoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getLiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEventDecoder(): Decoder<LiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEvent> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['newAuthority', getAddressDecoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getLiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEventCodec(): Codec<
  LiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEventArgs,
  LiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEvent
> {
  return combineCodec(
    getLiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEventEncoder(),
    getLiquidityPoolInstructionsAdminUpdateAmmsConfigsManagerAuthorityUpdateAmmsConfigsManagerAuthorityEventDecoder()
  );
}
