/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type UpdateAmmsConfigsManagerHeadAuthorityEvent = {
  headAuthority: Address;
  newHeadAuthority: Address;
  timestamp: bigint;
};

export type UpdateAmmsConfigsManagerHeadAuthorityEventArgs = {
  headAuthority: Address;
  newHeadAuthority: Address;
  timestamp: number | bigint;
};

export function getUpdateAmmsConfigsManagerHeadAuthorityEventEncoder(): Encoder<UpdateAmmsConfigsManagerHeadAuthorityEventArgs> {
  return getStructEncoder([
    ['headAuthority', getAddressEncoder()],
    ['newHeadAuthority', getAddressEncoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getUpdateAmmsConfigsManagerHeadAuthorityEventDecoder(): Decoder<UpdateAmmsConfigsManagerHeadAuthorityEvent> {
  return getStructDecoder([
    ['headAuthority', getAddressDecoder()],
    ['newHeadAuthority', getAddressDecoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getUpdateAmmsConfigsManagerHeadAuthorityEventCodec(): Codec<
  UpdateAmmsConfigsManagerHeadAuthorityEventArgs,
  UpdateAmmsConfigsManagerHeadAuthorityEvent
> {
  return combineCodec(
    getUpdateAmmsConfigsManagerHeadAuthorityEventEncoder(),
    getUpdateAmmsConfigsManagerHeadAuthorityEventDecoder()
  );
}
