/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type UpdateAmmsConfigProtocolFeeRateEvent = {
  authority: Address;
  ammsConfig: Address;
  newProtocolFeeRateBasisPoints: number;
  timestamp: bigint;
};

export type UpdateAmmsConfigProtocolFeeRateEventArgs = {
  authority: Address;
  ammsConfig: Address;
  newProtocolFeeRateBasisPoints: number;
  timestamp: number | bigint;
};

export function getUpdateAmmsConfigProtocolFeeRateEventEncoder(): Encoder<UpdateAmmsConfigProtocolFeeRateEventArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['ammsConfig', getAddressEncoder()],
    ['newProtocolFeeRateBasisPoints', getU16Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getUpdateAmmsConfigProtocolFeeRateEventDecoder(): Decoder<UpdateAmmsConfigProtocolFeeRateEvent> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['ammsConfig', getAddressDecoder()],
    ['newProtocolFeeRateBasisPoints', getU16Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getUpdateAmmsConfigProtocolFeeRateEventCodec(): Codec<
  UpdateAmmsConfigProtocolFeeRateEventArgs,
  UpdateAmmsConfigProtocolFeeRateEvent
> {
  return combineCodec(
    getUpdateAmmsConfigProtocolFeeRateEventEncoder(),
    getUpdateAmmsConfigProtocolFeeRateEventDecoder()
  );
}
