/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type UpdateAmmsConfigFeeAuthorityEvent = {
  authority: Address;
  ammsConfig: Address;
  newFeeAuthority: Address;
  timestamp: bigint;
};

export type UpdateAmmsConfigFeeAuthorityEventArgs = {
  authority: Address;
  ammsConfig: Address;
  newFeeAuthority: Address;
  timestamp: number | bigint;
};

export function getUpdateAmmsConfigFeeAuthorityEventEncoder(): Encoder<UpdateAmmsConfigFeeAuthorityEventArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['ammsConfig', getAddressEncoder()],
    ['newFeeAuthority', getAddressEncoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getUpdateAmmsConfigFeeAuthorityEventDecoder(): Decoder<UpdateAmmsConfigFeeAuthorityEvent> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['ammsConfig', getAddressDecoder()],
    ['newFeeAuthority', getAddressDecoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getUpdateAmmsConfigFeeAuthorityEventCodec(): Codec<
  UpdateAmmsConfigFeeAuthorityEventArgs,
  UpdateAmmsConfigFeeAuthorityEvent
> {
  return combineCodec(
    getUpdateAmmsConfigFeeAuthorityEventEncoder(),
    getUpdateAmmsConfigFeeAuthorityEventDecoder()
  );
}
