//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

      pub(crate) mod liquidity_pool;
  
      pub use self::liquidity_pool::LiquidityPoolError;
  
