[package]
name = "utilities"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
anchor-spl = "0.30.1"
uint = { version = "0.10.0"}

[dev-dependencies]
proptest = "1.6.0"