[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
launchpool = "5M9TeHHBeAtUd956yRUW9TEULF5XqGUdcyfy74YDzXHU"
liquidity_pool = "2M2QKXZuuERizynTpUwfD7FkdhKHWAFVKiCFGBSxXr3X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "owner.json"

[scripts]
generate-clients = "ts-node ./scripts/generate-clients.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/launchpool.ts tests/liquidity-pool.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
