//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum LaunchpoolError {
    /// 6000 - Stake position is already initialized.
    #[error("Stake position is already initialized.")]
    StakePositionAlreadyInitialized = 0x1770,
    /// 6001 - Invalid state for opening a stake position.
    #[error("Invalid state for opening a stake position.")]
    InvalidStakePositionStateForOpen = 0x1771,
    /// 6002 - Stake position is not opened.
    #[error("Stake position is not opened.")]
    StakePositionNotOpened = 0x1772,
    /// 6003 - Launchpool provided does not match the one stored in the position.
    #[error("Launchpool provided does not match the one stored in the position.")]
    MismatchedLaunchpool = 0x1773,
    /// 6004 - Stake amount must be greater than zero.
    #[error("Stake amount must be greater than zero.")]
    StakeAmountIsZero = 0x1774,
    /// 6005 - Stake amount is below the minimum allowed.
    #[error("Stake amount is below the minimum allowed.")]
    StakeBelowMinimum = 0x1775,
    /// 6006 - Stake amount exceeds the maximum allowed.
    #[error("Stake amount exceeds the maximum allowed.")]
    StakeAboveMaximum = 0x1776,
    /// 6007 - Overflow occurred during reward accumulation.
    #[error("Overflow occurred during reward accumulation.")]
    RewardAccumulationOverflow = 0x1777,
    /// 6008 - Reward debt is greater than total accrued reward.
    #[error("Reward debt is greater than total accrued reward.")]
    RewardDebtExceedsAccrued = 0x1778,
    /// 6009 - Overflow occurred while adding pending reward.
    #[error("Overflow occurred while adding pending reward.")]
    RewardOverflow = 0x1779,
    /// 6010 - Overflow occurred while increasing staked amount.
    #[error("Overflow occurred while increasing staked amount.")]
    StakeOverflow = 0x177A,
    /// 6011 - Overflow occurred while calculating reward debt.
    #[error("Overflow occurred while calculating reward debt.")]
    RewardDebtCalculationOverflow = 0x177B,
}

impl solana_program::program_error::PrintProgramError for LaunchpoolError {
    fn print<E>(&self) {
        solana_program::msg!(&self.to_string());
    }
}

impl<T> solana_program::decode_error::DecodeError<T> for LaunchpoolError {
    fn type_of() -> &'static str {
        "LaunchpoolError"
    }
}

