/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { LAUNCHPOOL_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const LAUNCH_LAUNCHPOOL_DISCRIMINATOR = new Uint8Array([
  97, 196, 50, 30, 168, 108, 120, 59,
]);

export function getLaunchLaunchpoolDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    LAUNCH_LAUNCHPOOL_DISCRIMINATOR
  );
}

export type LaunchLaunchpoolInstruction<
  TProgram extends string = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountLaunchpoolsConfigsManager extends
    | string
    | IAccountMeta<string> = string,
  TAccountLaunchpoolsConfig extends string | IAccountMeta<string> = string,
  TAccountRewardMint extends string | IAccountMeta<string> = string,
  TAccountLaunchpool extends string | IAccountMeta<string> = string,
  TAccountRewardVault extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountLaunchpoolsConfigsManager extends string
        ? ReadonlyAccount<TAccountLaunchpoolsConfigsManager>
        : TAccountLaunchpoolsConfigsManager,
      TAccountLaunchpoolsConfig extends string
        ? ReadonlyAccount<TAccountLaunchpoolsConfig>
        : TAccountLaunchpoolsConfig,
      TAccountRewardMint extends string
        ? ReadonlyAccount<TAccountRewardMint>
        : TAccountRewardMint,
      TAccountLaunchpool extends string
        ? WritableAccount<TAccountLaunchpool>
        : TAccountLaunchpool,
      TAccountRewardVault extends string
        ? WritableAccount<TAccountRewardVault>
        : TAccountRewardVault,
      ...TRemainingAccounts,
    ]
  >;

export type LaunchLaunchpoolInstructionData = {
  discriminator: ReadonlyUint8Array;
  startTimestamp: bigint;
};

export type LaunchLaunchpoolInstructionDataArgs = {
  startTimestamp: number | bigint;
};

export function getLaunchLaunchpoolInstructionDataEncoder(): Encoder<LaunchLaunchpoolInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['startTimestamp', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: LAUNCH_LAUNCHPOOL_DISCRIMINATOR })
  );
}

export function getLaunchLaunchpoolInstructionDataDecoder(): Decoder<LaunchLaunchpoolInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['startTimestamp', getU64Decoder()],
  ]);
}

export function getLaunchLaunchpoolInstructionDataCodec(): Codec<
  LaunchLaunchpoolInstructionDataArgs,
  LaunchLaunchpoolInstructionData
> {
  return combineCodec(
    getLaunchLaunchpoolInstructionDataEncoder(),
    getLaunchLaunchpoolInstructionDataDecoder()
  );
}

export type LaunchLaunchpoolAsyncInput<
  TAccountAuthority extends string = string,
  TAccountLaunchpoolsConfigsManager extends string = string,
  TAccountLaunchpoolsConfig extends string = string,
  TAccountRewardMint extends string = string,
  TAccountLaunchpool extends string = string,
  TAccountRewardVault extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  launchpoolsConfigsManager?: Address<TAccountLaunchpoolsConfigsManager>;
  launchpoolsConfig: Address<TAccountLaunchpoolsConfig>;
  rewardMint: Address<TAccountRewardMint>;
  launchpool: Address<TAccountLaunchpool>;
  rewardVault?: Address<TAccountRewardVault>;
  startTimestamp: LaunchLaunchpoolInstructionDataArgs['startTimestamp'];
};

export async function getLaunchLaunchpoolInstructionAsync<
  TAccountAuthority extends string,
  TAccountLaunchpoolsConfigsManager extends string,
  TAccountLaunchpoolsConfig extends string,
  TAccountRewardMint extends string,
  TAccountLaunchpool extends string,
  TAccountRewardVault extends string,
  TProgramAddress extends Address = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
>(
  input: LaunchLaunchpoolAsyncInput<
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig,
    TAccountRewardMint,
    TAccountLaunchpool,
    TAccountRewardVault
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  LaunchLaunchpoolInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig,
    TAccountRewardMint,
    TAccountLaunchpool,
    TAccountRewardVault
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? LAUNCHPOOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    launchpoolsConfigsManager: {
      value: input.launchpoolsConfigsManager ?? null,
      isWritable: false,
    },
    launchpoolsConfig: {
      value: input.launchpoolsConfig ?? null,
      isWritable: false,
    },
    rewardMint: { value: input.rewardMint ?? null, isWritable: false },
    launchpool: { value: input.launchpool ?? null, isWritable: true },
    rewardVault: { value: input.rewardVault ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.launchpoolsConfigsManager.value) {
    accounts.launchpoolsConfigsManager.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            108, 97, 117, 110, 99, 104, 112, 111, 111, 108, 115, 95, 99, 111,
            110, 102, 105, 103, 115, 95, 109, 97, 110, 97, 103, 101, 114,
          ])
        ),
      ],
    });
  }
  if (!accounts.rewardVault.value) {
    accounts.rewardVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116])),
        getAddressEncoder().encode(expectAddress(accounts.launchpool.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.launchpoolsConfigsManager),
      getAccountMeta(accounts.launchpoolsConfig),
      getAccountMeta(accounts.rewardMint),
      getAccountMeta(accounts.launchpool),
      getAccountMeta(accounts.rewardVault),
    ],
    programAddress,
    data: getLaunchLaunchpoolInstructionDataEncoder().encode(
      args as LaunchLaunchpoolInstructionDataArgs
    ),
  } as LaunchLaunchpoolInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig,
    TAccountRewardMint,
    TAccountLaunchpool,
    TAccountRewardVault
  >;

  return instruction;
}

export type LaunchLaunchpoolInput<
  TAccountAuthority extends string = string,
  TAccountLaunchpoolsConfigsManager extends string = string,
  TAccountLaunchpoolsConfig extends string = string,
  TAccountRewardMint extends string = string,
  TAccountLaunchpool extends string = string,
  TAccountRewardVault extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  launchpoolsConfigsManager: Address<TAccountLaunchpoolsConfigsManager>;
  launchpoolsConfig: Address<TAccountLaunchpoolsConfig>;
  rewardMint: Address<TAccountRewardMint>;
  launchpool: Address<TAccountLaunchpool>;
  rewardVault: Address<TAccountRewardVault>;
  startTimestamp: LaunchLaunchpoolInstructionDataArgs['startTimestamp'];
};

export function getLaunchLaunchpoolInstruction<
  TAccountAuthority extends string,
  TAccountLaunchpoolsConfigsManager extends string,
  TAccountLaunchpoolsConfig extends string,
  TAccountRewardMint extends string,
  TAccountLaunchpool extends string,
  TAccountRewardVault extends string,
  TProgramAddress extends Address = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
>(
  input: LaunchLaunchpoolInput<
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig,
    TAccountRewardMint,
    TAccountLaunchpool,
    TAccountRewardVault
  >,
  config?: { programAddress?: TProgramAddress }
): LaunchLaunchpoolInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountLaunchpoolsConfigsManager,
  TAccountLaunchpoolsConfig,
  TAccountRewardMint,
  TAccountLaunchpool,
  TAccountRewardVault
> {
  // Program address.
  const programAddress = config?.programAddress ?? LAUNCHPOOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    launchpoolsConfigsManager: {
      value: input.launchpoolsConfigsManager ?? null,
      isWritable: false,
    },
    launchpoolsConfig: {
      value: input.launchpoolsConfig ?? null,
      isWritable: false,
    },
    rewardMint: { value: input.rewardMint ?? null, isWritable: false },
    launchpool: { value: input.launchpool ?? null, isWritable: true },
    rewardVault: { value: input.rewardVault ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.launchpoolsConfigsManager),
      getAccountMeta(accounts.launchpoolsConfig),
      getAccountMeta(accounts.rewardMint),
      getAccountMeta(accounts.launchpool),
      getAccountMeta(accounts.rewardVault),
    ],
    programAddress,
    data: getLaunchLaunchpoolInstructionDataEncoder().encode(
      args as LaunchLaunchpoolInstructionDataArgs
    ),
  } as LaunchLaunchpoolInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig,
    TAccountRewardMint,
    TAccountLaunchpool,
    TAccountRewardVault
  >;

  return instruction;
}

export type ParsedLaunchLaunchpoolInstruction<
  TProgram extends string = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    launchpoolsConfigsManager: TAccountMetas[1];
    launchpoolsConfig: TAccountMetas[2];
    rewardMint: TAccountMetas[3];
    launchpool: TAccountMetas[4];
    rewardVault: TAccountMetas[5];
  };
  data: LaunchLaunchpoolInstructionData;
};

export function parseLaunchLaunchpoolInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedLaunchLaunchpoolInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      launchpoolsConfigsManager: getNextAccount(),
      launchpoolsConfig: getNextAccount(),
      rewardMint: getNextAccount(),
      launchpool: getNextAccount(),
      rewardVault: getNextAccount(),
    },
    data: getLaunchLaunchpoolInstructionDataDecoder().decode(instruction.data),
  };
}
