/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { LAUNCHPOOL_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_LAUNCHPOOLS_CONFIG_POSITION_SIZES_DISCRIMINATOR =
  new Uint8Array([216, 176, 23, 53, 154, 201, 212, 172]);

export function getUpdateLaunchpoolsConfigPositionSizesDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_LAUNCHPOOLS_CONFIG_POSITION_SIZES_DISCRIMINATOR
  );
}

export type UpdateLaunchpoolsConfigPositionSizesInstruction<
  TProgram extends string = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountLaunchpoolsConfigsManager extends
    | string
    | IAccountMeta<string> = string,
  TAccountLaunchpoolsConfig extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountLaunchpoolsConfigsManager extends string
        ? ReadonlyAccount<TAccountLaunchpoolsConfigsManager>
        : TAccountLaunchpoolsConfigsManager,
      TAccountLaunchpoolsConfig extends string
        ? WritableAccount<TAccountLaunchpoolsConfig>
        : TAccountLaunchpoolsConfig,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateLaunchpoolsConfigPositionSizesInstructionData = {
  discriminator: ReadonlyUint8Array;
  newMinPositionSize: bigint;
  newMaxPositionSize: bigint;
};

export type UpdateLaunchpoolsConfigPositionSizesInstructionDataArgs = {
  newMinPositionSize: number | bigint;
  newMaxPositionSize: number | bigint;
};

export function getUpdateLaunchpoolsConfigPositionSizesInstructionDataEncoder(): Encoder<UpdateLaunchpoolsConfigPositionSizesInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['newMinPositionSize', getU64Encoder()],
      ['newMaxPositionSize', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_LAUNCHPOOLS_CONFIG_POSITION_SIZES_DISCRIMINATOR,
    })
  );
}

export function getUpdateLaunchpoolsConfigPositionSizesInstructionDataDecoder(): Decoder<UpdateLaunchpoolsConfigPositionSizesInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['newMinPositionSize', getU64Decoder()],
    ['newMaxPositionSize', getU64Decoder()],
  ]);
}

export function getUpdateLaunchpoolsConfigPositionSizesInstructionDataCodec(): Codec<
  UpdateLaunchpoolsConfigPositionSizesInstructionDataArgs,
  UpdateLaunchpoolsConfigPositionSizesInstructionData
> {
  return combineCodec(
    getUpdateLaunchpoolsConfigPositionSizesInstructionDataEncoder(),
    getUpdateLaunchpoolsConfigPositionSizesInstructionDataDecoder()
  );
}

export type UpdateLaunchpoolsConfigPositionSizesAsyncInput<
  TAccountAuthority extends string = string,
  TAccountLaunchpoolsConfigsManager extends string = string,
  TAccountLaunchpoolsConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  launchpoolsConfigsManager?: Address<TAccountLaunchpoolsConfigsManager>;
  launchpoolsConfig: Address<TAccountLaunchpoolsConfig>;
  newMinPositionSize: UpdateLaunchpoolsConfigPositionSizesInstructionDataArgs['newMinPositionSize'];
  newMaxPositionSize: UpdateLaunchpoolsConfigPositionSizesInstructionDataArgs['newMaxPositionSize'];
};

export async function getUpdateLaunchpoolsConfigPositionSizesInstructionAsync<
  TAccountAuthority extends string,
  TAccountLaunchpoolsConfigsManager extends string,
  TAccountLaunchpoolsConfig extends string,
  TProgramAddress extends Address = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
>(
  input: UpdateLaunchpoolsConfigPositionSizesAsyncInput<
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  UpdateLaunchpoolsConfigPositionSizesInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? LAUNCHPOOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    launchpoolsConfigsManager: {
      value: input.launchpoolsConfigsManager ?? null,
      isWritable: false,
    },
    launchpoolsConfig: {
      value: input.launchpoolsConfig ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.launchpoolsConfigsManager.value) {
    accounts.launchpoolsConfigsManager.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            108, 97, 117, 110, 99, 104, 112, 111, 111, 108, 115, 95, 99, 111,
            110, 102, 105, 103, 115, 95, 109, 97, 110, 97, 103, 101, 114,
          ])
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.launchpoolsConfigsManager),
      getAccountMeta(accounts.launchpoolsConfig),
    ],
    programAddress,
    data: getUpdateLaunchpoolsConfigPositionSizesInstructionDataEncoder().encode(
      args as UpdateLaunchpoolsConfigPositionSizesInstructionDataArgs
    ),
  } as UpdateLaunchpoolsConfigPositionSizesInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig
  >;

  return instruction;
}

export type UpdateLaunchpoolsConfigPositionSizesInput<
  TAccountAuthority extends string = string,
  TAccountLaunchpoolsConfigsManager extends string = string,
  TAccountLaunchpoolsConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  launchpoolsConfigsManager: Address<TAccountLaunchpoolsConfigsManager>;
  launchpoolsConfig: Address<TAccountLaunchpoolsConfig>;
  newMinPositionSize: UpdateLaunchpoolsConfigPositionSizesInstructionDataArgs['newMinPositionSize'];
  newMaxPositionSize: UpdateLaunchpoolsConfigPositionSizesInstructionDataArgs['newMaxPositionSize'];
};

export function getUpdateLaunchpoolsConfigPositionSizesInstruction<
  TAccountAuthority extends string,
  TAccountLaunchpoolsConfigsManager extends string,
  TAccountLaunchpoolsConfig extends string,
  TProgramAddress extends Address = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
>(
  input: UpdateLaunchpoolsConfigPositionSizesInput<
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateLaunchpoolsConfigPositionSizesInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountLaunchpoolsConfigsManager,
  TAccountLaunchpoolsConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? LAUNCHPOOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    launchpoolsConfigsManager: {
      value: input.launchpoolsConfigsManager ?? null,
      isWritable: false,
    },
    launchpoolsConfig: {
      value: input.launchpoolsConfig ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.launchpoolsConfigsManager),
      getAccountMeta(accounts.launchpoolsConfig),
    ],
    programAddress,
    data: getUpdateLaunchpoolsConfigPositionSizesInstructionDataEncoder().encode(
      args as UpdateLaunchpoolsConfigPositionSizesInstructionDataArgs
    ),
  } as UpdateLaunchpoolsConfigPositionSizesInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig
  >;

  return instruction;
}

export type ParsedUpdateLaunchpoolsConfigPositionSizesInstruction<
  TProgram extends string = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    launchpoolsConfigsManager: TAccountMetas[1];
    launchpoolsConfig: TAccountMetas[2];
  };
  data: UpdateLaunchpoolsConfigPositionSizesInstructionData;
};

export function parseUpdateLaunchpoolsConfigPositionSizesInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedUpdateLaunchpoolsConfigPositionSizesInstruction<
  TProgram,
  TAccountMetas
> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      launchpoolsConfigsManager: getNextAccount(),
      launchpoolsConfig: getNextAccount(),
    },
    data: getUpdateLaunchpoolsConfigPositionSizesInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
