/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { LAUNCHPOOL_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_LAUNCHPOOLS_CONFIGS_MANAGER_HEAD_AUTHORITY_DISCRIMINATOR =
  new Uint8Array([208, 235, 147, 149, 161, 117, 147, 222]);

export function getUpdateLaunchpoolsConfigsManagerHeadAuthorityDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_LAUNCHPOOLS_CONFIGS_MANAGER_HEAD_AUTHORITY_DISCRIMINATOR
  );
}

export type UpdateLaunchpoolsConfigsManagerHeadAuthorityInstruction<
  TProgram extends string = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
  TAccountHeadAuthority extends string | IAccountMeta<string> = string,
  TAccountLaunchpoolsConfigsManager extends
    | string
    | IAccountMeta<string> = string,
  TAccountNewHeadAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountHeadAuthority extends string
        ? WritableSignerAccount<TAccountHeadAuthority> &
            IAccountSignerMeta<TAccountHeadAuthority>
        : TAccountHeadAuthority,
      TAccountLaunchpoolsConfigsManager extends string
        ? WritableAccount<TAccountLaunchpoolsConfigsManager>
        : TAccountLaunchpoolsConfigsManager,
      TAccountNewHeadAuthority extends string
        ? ReadonlyAccount<TAccountNewHeadAuthority>
        : TAccountNewHeadAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type UpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataArgs =
  {};

export function getUpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataEncoder(): Encoder<UpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator:
        UPDATE_LAUNCHPOOLS_CONFIGS_MANAGER_HEAD_AUTHORITY_DISCRIMINATOR,
    })
  );
}

export function getUpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataDecoder(): Decoder<UpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getUpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataCodec(): Codec<
  UpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataArgs,
  UpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionData
> {
  return combineCodec(
    getUpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataEncoder(),
    getUpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataDecoder()
  );
}

export type UpdateLaunchpoolsConfigsManagerHeadAuthorityAsyncInput<
  TAccountHeadAuthority extends string = string,
  TAccountLaunchpoolsConfigsManager extends string = string,
  TAccountNewHeadAuthority extends string = string,
> = {
  headAuthority: TransactionSigner<TAccountHeadAuthority>;
  launchpoolsConfigsManager?: Address<TAccountLaunchpoolsConfigsManager>;
  newHeadAuthority: Address<TAccountNewHeadAuthority>;
};

export async function getUpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionAsync<
  TAccountHeadAuthority extends string,
  TAccountLaunchpoolsConfigsManager extends string,
  TAccountNewHeadAuthority extends string,
  TProgramAddress extends Address = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
>(
  input: UpdateLaunchpoolsConfigsManagerHeadAuthorityAsyncInput<
    TAccountHeadAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountNewHeadAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  UpdateLaunchpoolsConfigsManagerHeadAuthorityInstruction<
    TProgramAddress,
    TAccountHeadAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountNewHeadAuthority
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? LAUNCHPOOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    headAuthority: { value: input.headAuthority ?? null, isWritable: true },
    launchpoolsConfigsManager: {
      value: input.launchpoolsConfigsManager ?? null,
      isWritable: true,
    },
    newHeadAuthority: {
      value: input.newHeadAuthority ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.launchpoolsConfigsManager.value) {
    accounts.launchpoolsConfigsManager.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            108, 97, 117, 110, 99, 104, 112, 111, 111, 108, 115, 95, 99, 111,
            110, 102, 105, 103, 115, 95, 109, 97, 110, 97, 103, 101, 114,
          ])
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.headAuthority),
      getAccountMeta(accounts.launchpoolsConfigsManager),
      getAccountMeta(accounts.newHeadAuthority),
    ],
    programAddress,
    data: getUpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataEncoder().encode(
      {}
    ),
  } as UpdateLaunchpoolsConfigsManagerHeadAuthorityInstruction<
    TProgramAddress,
    TAccountHeadAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountNewHeadAuthority
  >;

  return instruction;
}

export type UpdateLaunchpoolsConfigsManagerHeadAuthorityInput<
  TAccountHeadAuthority extends string = string,
  TAccountLaunchpoolsConfigsManager extends string = string,
  TAccountNewHeadAuthority extends string = string,
> = {
  headAuthority: TransactionSigner<TAccountHeadAuthority>;
  launchpoolsConfigsManager: Address<TAccountLaunchpoolsConfigsManager>;
  newHeadAuthority: Address<TAccountNewHeadAuthority>;
};

export function getUpdateLaunchpoolsConfigsManagerHeadAuthorityInstruction<
  TAccountHeadAuthority extends string,
  TAccountLaunchpoolsConfigsManager extends string,
  TAccountNewHeadAuthority extends string,
  TProgramAddress extends Address = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
>(
  input: UpdateLaunchpoolsConfigsManagerHeadAuthorityInput<
    TAccountHeadAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountNewHeadAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateLaunchpoolsConfigsManagerHeadAuthorityInstruction<
  TProgramAddress,
  TAccountHeadAuthority,
  TAccountLaunchpoolsConfigsManager,
  TAccountNewHeadAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? LAUNCHPOOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    headAuthority: { value: input.headAuthority ?? null, isWritable: true },
    launchpoolsConfigsManager: {
      value: input.launchpoolsConfigsManager ?? null,
      isWritable: true,
    },
    newHeadAuthority: {
      value: input.newHeadAuthority ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.headAuthority),
      getAccountMeta(accounts.launchpoolsConfigsManager),
      getAccountMeta(accounts.newHeadAuthority),
    ],
    programAddress,
    data: getUpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataEncoder().encode(
      {}
    ),
  } as UpdateLaunchpoolsConfigsManagerHeadAuthorityInstruction<
    TProgramAddress,
    TAccountHeadAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountNewHeadAuthority
  >;

  return instruction;
}

export type ParsedUpdateLaunchpoolsConfigsManagerHeadAuthorityInstruction<
  TProgram extends string = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    headAuthority: TAccountMetas[0];
    launchpoolsConfigsManager: TAccountMetas[1];
    newHeadAuthority: TAccountMetas[2];
  };
  data: UpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionData;
};

export function parseUpdateLaunchpoolsConfigsManagerHeadAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedUpdateLaunchpoolsConfigsManagerHeadAuthorityInstruction<
  TProgram,
  TAccountMetas
> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      headAuthority: getNextAccount(),
      launchpoolsConfigsManager: getNextAccount(),
      newHeadAuthority: getNextAccount(),
    },
    data: getUpdateLaunchpoolsConfigsManagerHeadAuthorityInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
