/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { LAUNCHPOOL_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_LAUNCHPOOLS_CONFIG_REWARD_AUTHORITY_DISCRIMINATOR =
  new Uint8Array([129, 70, 231, 58, 103, 47, 83, 57]);

export function getUpdateLaunchpoolsConfigRewardAuthorityDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_LAUNCHPOOLS_CONFIG_REWARD_AUTHORITY_DISCRIMINATOR
  );
}

export type UpdateLaunchpoolsConfigRewardAuthorityInstruction<
  TProgram extends string = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountLaunchpoolsConfigsManager extends
    | string
    | IAccountMeta<string> = string,
  TAccountLaunchpoolsConfig extends string | IAccountMeta<string> = string,
  TAccountNewRewardAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountLaunchpoolsConfigsManager extends string
        ? ReadonlyAccount<TAccountLaunchpoolsConfigsManager>
        : TAccountLaunchpoolsConfigsManager,
      TAccountLaunchpoolsConfig extends string
        ? WritableAccount<TAccountLaunchpoolsConfig>
        : TAccountLaunchpoolsConfig,
      TAccountNewRewardAuthority extends string
        ? ReadonlyAccount<TAccountNewRewardAuthority>
        : TAccountNewRewardAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateLaunchpoolsConfigRewardAuthorityInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type UpdateLaunchpoolsConfigRewardAuthorityInstructionDataArgs = {};

export function getUpdateLaunchpoolsConfigRewardAuthorityInstructionDataEncoder(): Encoder<UpdateLaunchpoolsConfigRewardAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: UPDATE_LAUNCHPOOLS_CONFIG_REWARD_AUTHORITY_DISCRIMINATOR,
    })
  );
}

export function getUpdateLaunchpoolsConfigRewardAuthorityInstructionDataDecoder(): Decoder<UpdateLaunchpoolsConfigRewardAuthorityInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getUpdateLaunchpoolsConfigRewardAuthorityInstructionDataCodec(): Codec<
  UpdateLaunchpoolsConfigRewardAuthorityInstructionDataArgs,
  UpdateLaunchpoolsConfigRewardAuthorityInstructionData
> {
  return combineCodec(
    getUpdateLaunchpoolsConfigRewardAuthorityInstructionDataEncoder(),
    getUpdateLaunchpoolsConfigRewardAuthorityInstructionDataDecoder()
  );
}

export type UpdateLaunchpoolsConfigRewardAuthorityAsyncInput<
  TAccountAuthority extends string = string,
  TAccountLaunchpoolsConfigsManager extends string = string,
  TAccountLaunchpoolsConfig extends string = string,
  TAccountNewRewardAuthority extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  launchpoolsConfigsManager?: Address<TAccountLaunchpoolsConfigsManager>;
  launchpoolsConfig: Address<TAccountLaunchpoolsConfig>;
  newRewardAuthority: Address<TAccountNewRewardAuthority>;
};

export async function getUpdateLaunchpoolsConfigRewardAuthorityInstructionAsync<
  TAccountAuthority extends string,
  TAccountLaunchpoolsConfigsManager extends string,
  TAccountLaunchpoolsConfig extends string,
  TAccountNewRewardAuthority extends string,
  TProgramAddress extends Address = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
>(
  input: UpdateLaunchpoolsConfigRewardAuthorityAsyncInput<
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig,
    TAccountNewRewardAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  UpdateLaunchpoolsConfigRewardAuthorityInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig,
    TAccountNewRewardAuthority
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? LAUNCHPOOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    launchpoolsConfigsManager: {
      value: input.launchpoolsConfigsManager ?? null,
      isWritable: false,
    },
    launchpoolsConfig: {
      value: input.launchpoolsConfig ?? null,
      isWritable: true,
    },
    newRewardAuthority: {
      value: input.newRewardAuthority ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.launchpoolsConfigsManager.value) {
    accounts.launchpoolsConfigsManager.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            108, 97, 117, 110, 99, 104, 112, 111, 111, 108, 115, 95, 99, 111,
            110, 102, 105, 103, 115, 95, 109, 97, 110, 97, 103, 101, 114,
          ])
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.launchpoolsConfigsManager),
      getAccountMeta(accounts.launchpoolsConfig),
      getAccountMeta(accounts.newRewardAuthority),
    ],
    programAddress,
    data: getUpdateLaunchpoolsConfigRewardAuthorityInstructionDataEncoder().encode(
      {}
    ),
  } as UpdateLaunchpoolsConfigRewardAuthorityInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig,
    TAccountNewRewardAuthority
  >;

  return instruction;
}

export type UpdateLaunchpoolsConfigRewardAuthorityInput<
  TAccountAuthority extends string = string,
  TAccountLaunchpoolsConfigsManager extends string = string,
  TAccountLaunchpoolsConfig extends string = string,
  TAccountNewRewardAuthority extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  launchpoolsConfigsManager: Address<TAccountLaunchpoolsConfigsManager>;
  launchpoolsConfig: Address<TAccountLaunchpoolsConfig>;
  newRewardAuthority: Address<TAccountNewRewardAuthority>;
};

export function getUpdateLaunchpoolsConfigRewardAuthorityInstruction<
  TAccountAuthority extends string,
  TAccountLaunchpoolsConfigsManager extends string,
  TAccountLaunchpoolsConfig extends string,
  TAccountNewRewardAuthority extends string,
  TProgramAddress extends Address = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
>(
  input: UpdateLaunchpoolsConfigRewardAuthorityInput<
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig,
    TAccountNewRewardAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateLaunchpoolsConfigRewardAuthorityInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountLaunchpoolsConfigsManager,
  TAccountLaunchpoolsConfig,
  TAccountNewRewardAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? LAUNCHPOOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    launchpoolsConfigsManager: {
      value: input.launchpoolsConfigsManager ?? null,
      isWritable: false,
    },
    launchpoolsConfig: {
      value: input.launchpoolsConfig ?? null,
      isWritable: true,
    },
    newRewardAuthority: {
      value: input.newRewardAuthority ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.launchpoolsConfigsManager),
      getAccountMeta(accounts.launchpoolsConfig),
      getAccountMeta(accounts.newRewardAuthority),
    ],
    programAddress,
    data: getUpdateLaunchpoolsConfigRewardAuthorityInstructionDataEncoder().encode(
      {}
    ),
  } as UpdateLaunchpoolsConfigRewardAuthorityInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountLaunchpoolsConfigsManager,
    TAccountLaunchpoolsConfig,
    TAccountNewRewardAuthority
  >;

  return instruction;
}

export type ParsedUpdateLaunchpoolsConfigRewardAuthorityInstruction<
  TProgram extends string = typeof LAUNCHPOOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    launchpoolsConfigsManager: TAccountMetas[1];
    launchpoolsConfig: TAccountMetas[2];
    newRewardAuthority: TAccountMetas[3];
  };
  data: UpdateLaunchpoolsConfigRewardAuthorityInstructionData;
};

export function parseUpdateLaunchpoolsConfigRewardAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedUpdateLaunchpoolsConfigRewardAuthorityInstruction<
  TProgram,
  TAccountMetas
> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      launchpoolsConfigsManager: getNextAccount(),
      launchpoolsConfig: getNextAccount(),
      newRewardAuthority: getNextAccount(),
    },
    data: getUpdateLaunchpoolsConfigRewardAuthorityInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
