//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// Accounts.
#[derive(Debug)]
pub struct ProvideToCpAmm {
      
              
          pub signer: solana_program::pubkey::Pubkey,
          
              
          pub base_mint: solana_program::pubkey::Pubkey,
          
              
          pub quote_mint: solana_program::pubkey::Pubkey,
          
              
          pub lp_mint: solana_program::pubkey::Pubkey,
          
              
          pub signer_base_account: solana_program::pubkey::Pubkey,
          
              
          pub signer_quote_account: solana_program::pubkey::Pubkey,
          
              
          pub signer_lp_account: solana_program::pubkey::Pubkey,
          
              
          pub amms_config: solana_program::pubkey::Pubkey,
          
              
          pub cp_amm: solana_program::pubkey::Pubkey,
          
              
          pub cp_amm_base_vault: solana_program::pubkey::Pubkey,
          
              
          pub cp_amm_quote_vault: solana_program::pubkey::Pubkey,
          
              
          pub associated_token_program: solana_program::pubkey::Pubkey,
          
              
          pub lp_token_program: solana_program::pubkey::Pubkey,
          
              
          pub base_token_program: solana_program::pubkey::Pubkey,
          
              
          pub quote_token_program: solana_program::pubkey::Pubkey,
          
              
          pub system_program: solana_program::pubkey::Pubkey,
      }

impl ProvideToCpAmm {
  pub fn instruction(&self, args: ProvideToCpAmmInstructionArgs) -> solana_program::instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: ProvideToCpAmmInstructionArgs, remaining_accounts: &[solana_program::instruction::AccountMeta]) -> solana_program::instruction::Instruction {
    let mut accounts = Vec::with_capacity(16+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            self.signer,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.base_mint,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.quote_mint,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.lp_mint,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.signer_base_account,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.signer_quote_account,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.signer_lp_account,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.amms_config,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.cp_amm,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.cp_amm_base_vault,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.cp_amm_quote_vault,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.associated_token_program,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.lp_token_program,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.base_token_program,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.quote_token_program,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = borsh::to_vec(&ProvideToCpAmmInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&args).unwrap();
      data.append(&mut args);
    
    solana_program::instruction::Instruction {
      program_id: crate::LIQUIDITY_POOL_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct ProvideToCpAmmInstructionData {
            discriminator: [u8; 8],
                  }

impl ProvideToCpAmmInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [228, 147, 253, 251, 242, 255, 110, 245],
                                              }
  }
}

impl Default for ProvideToCpAmmInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct ProvideToCpAmmInstructionArgs {
                  pub base_liquidity: u64,
                pub quote_liquidity: u64,
      }


/// Instruction builder for `ProvideToCpAmm`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` signer
          ///   1. `[]` base_mint
          ///   2. `[]` quote_mint
                ///   3. `[writable]` lp_mint
                ///   4. `[writable]` signer_base_account
                ///   5. `[writable]` signer_quote_account
                ///   6. `[writable]` signer_lp_account
          ///   7. `[]` amms_config
                ///   8. `[writable]` cp_amm
                ///   9. `[writable]` cp_amm_base_vault
                ///   10. `[writable]` cp_amm_quote_vault
                ///   11. `[optional]` associated_token_program (default to `ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL`)
                ///   12. `[optional]` lp_token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
          ///   13. `[]` base_token_program
          ///   14. `[]` quote_token_program
                ///   15. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct ProvideToCpAmmBuilder {
            signer: Option<solana_program::pubkey::Pubkey>,
                base_mint: Option<solana_program::pubkey::Pubkey>,
                quote_mint: Option<solana_program::pubkey::Pubkey>,
                lp_mint: Option<solana_program::pubkey::Pubkey>,
                signer_base_account: Option<solana_program::pubkey::Pubkey>,
                signer_quote_account: Option<solana_program::pubkey::Pubkey>,
                signer_lp_account: Option<solana_program::pubkey::Pubkey>,
                amms_config: Option<solana_program::pubkey::Pubkey>,
                cp_amm: Option<solana_program::pubkey::Pubkey>,
                cp_amm_base_vault: Option<solana_program::pubkey::Pubkey>,
                cp_amm_quote_vault: Option<solana_program::pubkey::Pubkey>,
                associated_token_program: Option<solana_program::pubkey::Pubkey>,
                lp_token_program: Option<solana_program::pubkey::Pubkey>,
                base_token_program: Option<solana_program::pubkey::Pubkey>,
                quote_token_program: Option<solana_program::pubkey::Pubkey>,
                system_program: Option<solana_program::pubkey::Pubkey>,
                        base_liquidity: Option<u64>,
                quote_liquidity: Option<u64>,
        __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl ProvideToCpAmmBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn signer(&mut self, signer: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.signer = Some(signer);
                    self
    }
            #[inline(always)]
    pub fn base_mint(&mut self, base_mint: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.base_mint = Some(base_mint);
                    self
    }
            #[inline(always)]
    pub fn quote_mint(&mut self, quote_mint: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.quote_mint = Some(quote_mint);
                    self
    }
            #[inline(always)]
    pub fn lp_mint(&mut self, lp_mint: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.lp_mint = Some(lp_mint);
                    self
    }
            #[inline(always)]
    pub fn signer_base_account(&mut self, signer_base_account: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.signer_base_account = Some(signer_base_account);
                    self
    }
            #[inline(always)]
    pub fn signer_quote_account(&mut self, signer_quote_account: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.signer_quote_account = Some(signer_quote_account);
                    self
    }
            #[inline(always)]
    pub fn signer_lp_account(&mut self, signer_lp_account: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.signer_lp_account = Some(signer_lp_account);
                    self
    }
            #[inline(always)]
    pub fn amms_config(&mut self, amms_config: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.amms_config = Some(amms_config);
                    self
    }
            #[inline(always)]
    pub fn cp_amm(&mut self, cp_amm: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.cp_amm = Some(cp_amm);
                    self
    }
            #[inline(always)]
    pub fn cp_amm_base_vault(&mut self, cp_amm_base_vault: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.cp_amm_base_vault = Some(cp_amm_base_vault);
                    self
    }
            #[inline(always)]
    pub fn cp_amm_quote_vault(&mut self, cp_amm_quote_vault: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.cp_amm_quote_vault = Some(cp_amm_quote_vault);
                    self
    }
            /// `[optional account, default to 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL']`
#[inline(always)]
    pub fn associated_token_program(&mut self, associated_token_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.associated_token_program = Some(associated_token_program);
                    self
    }
            /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
#[inline(always)]
    pub fn lp_token_program(&mut self, lp_token_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.lp_token_program = Some(lp_token_program);
                    self
    }
            #[inline(always)]
    pub fn base_token_program(&mut self, base_token_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.base_token_program = Some(base_token_program);
                    self
    }
            #[inline(always)]
    pub fn quote_token_program(&mut self, quote_token_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.quote_token_program = Some(quote_token_program);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn base_liquidity(&mut self, base_liquidity: u64) -> &mut Self {
        self.base_liquidity = Some(base_liquidity);
        self
      }
                #[inline(always)]
      pub fn quote_liquidity(&mut self, quote_liquidity: u64) -> &mut Self {
        self.quote_liquidity = Some(quote_liquidity);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_program::instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_program::instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_program::instruction::Instruction {
    let accounts = ProvideToCpAmm {
                              signer: self.signer.expect("signer is not set"),
                                        base_mint: self.base_mint.expect("base_mint is not set"),
                                        quote_mint: self.quote_mint.expect("quote_mint is not set"),
                                        lp_mint: self.lp_mint.expect("lp_mint is not set"),
                                        signer_base_account: self.signer_base_account.expect("signer_base_account is not set"),
                                        signer_quote_account: self.signer_quote_account.expect("signer_quote_account is not set"),
                                        signer_lp_account: self.signer_lp_account.expect("signer_lp_account is not set"),
                                        amms_config: self.amms_config.expect("amms_config is not set"),
                                        cp_amm: self.cp_amm.expect("cp_amm is not set"),
                                        cp_amm_base_vault: self.cp_amm_base_vault.expect("cp_amm_base_vault is not set"),
                                        cp_amm_quote_vault: self.cp_amm_quote_vault.expect("cp_amm_quote_vault is not set"),
                                        associated_token_program: self.associated_token_program.unwrap_or(solana_program::pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")),
                                        lp_token_program: self.lp_token_program.unwrap_or(solana_program::pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")),
                                        base_token_program: self.base_token_program.expect("base_token_program is not set"),
                                        quote_token_program: self.quote_token_program.expect("quote_token_program is not set"),
                                        system_program: self.system_program.unwrap_or(solana_program::pubkey!("11111111111111111111111111111111")),
                      };
          let args = ProvideToCpAmmInstructionArgs {
                                                              base_liquidity: self.base_liquidity.clone().expect("base_liquidity is not set"),
                                                                  quote_liquidity: self.quote_liquidity.clone().expect("quote_liquidity is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `provide_to_cp_amm` CPI accounts.
  pub struct ProvideToCpAmmCpiAccounts<'a, 'b> {
          
                    
              pub signer: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub base_mint: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub quote_mint: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub lp_mint: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub signer_base_account: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub signer_quote_account: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub signer_lp_account: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub amms_config: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub cp_amm: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub cp_amm_base_vault: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub cp_amm_quote_vault: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub associated_token_program: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub lp_token_program: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub base_token_program: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub quote_token_program: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_program::account_info::AccountInfo<'a>,
            }

/// `provide_to_cp_amm` CPI instruction.
pub struct ProvideToCpAmmCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_program::account_info::AccountInfo<'a>,
      
              
          pub signer: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub base_mint: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub quote_mint: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub lp_mint: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub signer_base_account: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub signer_quote_account: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub signer_lp_account: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub amms_config: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub cp_amm: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub cp_amm_base_vault: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub cp_amm_quote_vault: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub associated_token_program: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub lp_token_program: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub base_token_program: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub quote_token_program: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_program::account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: ProvideToCpAmmInstructionArgs,
  }

impl<'a, 'b> ProvideToCpAmmCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_program::account_info::AccountInfo<'a>,
          accounts: ProvideToCpAmmCpiAccounts<'a, 'b>,
              args: ProvideToCpAmmInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              signer: accounts.signer,
              base_mint: accounts.base_mint,
              quote_mint: accounts.quote_mint,
              lp_mint: accounts.lp_mint,
              signer_base_account: accounts.signer_base_account,
              signer_quote_account: accounts.signer_quote_account,
              signer_lp_account: accounts.signer_lp_account,
              amms_config: accounts.amms_config,
              cp_amm: accounts.cp_amm,
              cp_amm_base_vault: accounts.cp_amm_base_vault,
              cp_amm_quote_vault: accounts.cp_amm_quote_vault,
              associated_token_program: accounts.associated_token_program,
              lp_token_program: accounts.lp_token_program,
              base_token_program: accounts.base_token_program,
              quote_token_program: accounts.quote_token_program,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program::entrypoint::ProgramResult {
    let mut accounts = Vec::with_capacity(16+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            *self.signer.key,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.base_mint.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.quote_mint.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.lp_mint.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.signer_base_account.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.signer_quote_account.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.signer_lp_account.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.amms_config.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.cp_amm.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.cp_amm_base_vault.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.cp_amm_quote_vault.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.associated_token_program.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.lp_token_program.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.base_token_program.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.quote_token_program.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_program::instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = borsh::to_vec(&ProvideToCpAmmInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&self.__args).unwrap();
      data.append(&mut args);
    
    let instruction = solana_program::instruction::Instruction {
      program_id: crate::LIQUIDITY_POOL_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(17 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.signer.clone());
                        account_infos.push(self.base_mint.clone());
                        account_infos.push(self.quote_mint.clone());
                        account_infos.push(self.lp_mint.clone());
                        account_infos.push(self.signer_base_account.clone());
                        account_infos.push(self.signer_quote_account.clone());
                        account_infos.push(self.signer_lp_account.clone());
                        account_infos.push(self.amms_config.clone());
                        account_infos.push(self.cp_amm.clone());
                        account_infos.push(self.cp_amm_base_vault.clone());
                        account_infos.push(self.cp_amm_quote_vault.clone());
                        account_infos.push(self.associated_token_program.clone());
                        account_infos.push(self.lp_token_program.clone());
                        account_infos.push(self.base_token_program.clone());
                        account_infos.push(self.quote_token_program.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_program::program::invoke(&instruction, &account_infos)
    } else {
      solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `ProvideToCpAmm` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` signer
          ///   1. `[]` base_mint
          ///   2. `[]` quote_mint
                ///   3. `[writable]` lp_mint
                ///   4. `[writable]` signer_base_account
                ///   5. `[writable]` signer_quote_account
                ///   6. `[writable]` signer_lp_account
          ///   7. `[]` amms_config
                ///   8. `[writable]` cp_amm
                ///   9. `[writable]` cp_amm_base_vault
                ///   10. `[writable]` cp_amm_quote_vault
          ///   11. `[]` associated_token_program
          ///   12. `[]` lp_token_program
          ///   13. `[]` base_token_program
          ///   14. `[]` quote_token_program
          ///   15. `[]` system_program
#[derive(Clone, Debug)]
pub struct ProvideToCpAmmCpiBuilder<'a, 'b> {
  instruction: Box<ProvideToCpAmmCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ProvideToCpAmmCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(ProvideToCpAmmCpiBuilderInstruction {
      __program: program,
              signer: None,
              base_mint: None,
              quote_mint: None,
              lp_mint: None,
              signer_base_account: None,
              signer_quote_account: None,
              signer_lp_account: None,
              amms_config: None,
              cp_amm: None,
              cp_amm_base_vault: None,
              cp_amm_quote_vault: None,
              associated_token_program: None,
              lp_token_program: None,
              base_token_program: None,
              quote_token_program: None,
              system_program: None,
                                            base_liquidity: None,
                                quote_liquidity: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.signer = Some(signer);
                    self
    }
      #[inline(always)]
    pub fn base_mint(&mut self, base_mint: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.base_mint = Some(base_mint);
                    self
    }
      #[inline(always)]
    pub fn quote_mint(&mut self, quote_mint: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.quote_mint = Some(quote_mint);
                    self
    }
      #[inline(always)]
    pub fn lp_mint(&mut self, lp_mint: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.lp_mint = Some(lp_mint);
                    self
    }
      #[inline(always)]
    pub fn signer_base_account(&mut self, signer_base_account: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.signer_base_account = Some(signer_base_account);
                    self
    }
      #[inline(always)]
    pub fn signer_quote_account(&mut self, signer_quote_account: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.signer_quote_account = Some(signer_quote_account);
                    self
    }
      #[inline(always)]
    pub fn signer_lp_account(&mut self, signer_lp_account: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.signer_lp_account = Some(signer_lp_account);
                    self
    }
      #[inline(always)]
    pub fn amms_config(&mut self, amms_config: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.amms_config = Some(amms_config);
                    self
    }
      #[inline(always)]
    pub fn cp_amm(&mut self, cp_amm: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cp_amm = Some(cp_amm);
                    self
    }
      #[inline(always)]
    pub fn cp_amm_base_vault(&mut self, cp_amm_base_vault: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cp_amm_base_vault = Some(cp_amm_base_vault);
                    self
    }
      #[inline(always)]
    pub fn cp_amm_quote_vault(&mut self, cp_amm_quote_vault: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cp_amm_quote_vault = Some(cp_amm_quote_vault);
                    self
    }
      #[inline(always)]
    pub fn associated_token_program(&mut self, associated_token_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.associated_token_program = Some(associated_token_program);
                    self
    }
      #[inline(always)]
    pub fn lp_token_program(&mut self, lp_token_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.lp_token_program = Some(lp_token_program);
                    self
    }
      #[inline(always)]
    pub fn base_token_program(&mut self, base_token_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.base_token_program = Some(base_token_program);
                    self
    }
      #[inline(always)]
    pub fn quote_token_program(&mut self, quote_token_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.quote_token_program = Some(quote_token_program);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn base_liquidity(&mut self, base_liquidity: u64) -> &mut Self {
        self.instruction.base_liquidity = Some(base_liquidity);
        self
      }
                #[inline(always)]
      pub fn quote_liquidity(&mut self, quote_liquidity: u64) -> &mut Self {
        self.instruction.quote_liquidity = Some(quote_liquidity);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_program::account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
          let args = ProvideToCpAmmInstructionArgs {
                                                              base_liquidity: self.instruction.base_liquidity.clone().expect("base_liquidity is not set"),
                                                                  quote_liquidity: self.instruction.quote_liquidity.clone().expect("quote_liquidity is not set"),
                                    };
        let instruction = ProvideToCpAmmCpi {
        __program: self.instruction.__program,
                  
          signer: self.instruction.signer.expect("signer is not set"),
                  
          base_mint: self.instruction.base_mint.expect("base_mint is not set"),
                  
          quote_mint: self.instruction.quote_mint.expect("quote_mint is not set"),
                  
          lp_mint: self.instruction.lp_mint.expect("lp_mint is not set"),
                  
          signer_base_account: self.instruction.signer_base_account.expect("signer_base_account is not set"),
                  
          signer_quote_account: self.instruction.signer_quote_account.expect("signer_quote_account is not set"),
                  
          signer_lp_account: self.instruction.signer_lp_account.expect("signer_lp_account is not set"),
                  
          amms_config: self.instruction.amms_config.expect("amms_config is not set"),
                  
          cp_amm: self.instruction.cp_amm.expect("cp_amm is not set"),
                  
          cp_amm_base_vault: self.instruction.cp_amm_base_vault.expect("cp_amm_base_vault is not set"),
                  
          cp_amm_quote_vault: self.instruction.cp_amm_quote_vault.expect("cp_amm_quote_vault is not set"),
                  
          associated_token_program: self.instruction.associated_token_program.expect("associated_token_program is not set"),
                  
          lp_token_program: self.instruction.lp_token_program.expect("lp_token_program is not set"),
                  
          base_token_program: self.instruction.base_token_program.expect("base_token_program is not set"),
                  
          quote_token_program: self.instruction.quote_token_program.expect("quote_token_program is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct ProvideToCpAmmCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_program::account_info::AccountInfo<'a>,
            signer: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                base_mint: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                quote_mint: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                lp_mint: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                signer_base_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                signer_quote_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                signer_lp_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                amms_config: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                cp_amm: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                cp_amm_base_vault: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                cp_amm_quote_vault: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                associated_token_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                lp_token_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                base_token_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                quote_token_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                        base_liquidity: Option<u64>,
                quote_liquidity: Option<u64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)>,
}

