//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// Accounts.
#[derive(Debug)]
pub struct UpdateAmmsConfigProvidersFeeRate {
      
              
          pub authority: solana_program::pubkey::Pubkey,
          
              
          pub amms_configs_manager: solana_program::pubkey::Pubkey,
          
              
          pub amms_config: solana_program::pubkey::Pubkey,
      }

impl UpdateAmmsConfigProvidersFeeRate {
  pub fn instruction(&self, args: UpdateAmmsConfigProvidersFeeRateInstructionArgs) -> solana_program::instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: UpdateAmmsConfigProvidersFeeRateInstructionArgs, remaining_accounts: &[solana_program::instruction::AccountMeta]) -> solana_program::instruction::Instruction {
    let mut accounts = Vec::with_capacity(3+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            self.authority,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.amms_configs_manager,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.amms_config,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = borsh::to_vec(&UpdateAmmsConfigProvidersFeeRateInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&args).unwrap();
      data.append(&mut args);
    
    solana_program::instruction::Instruction {
      program_id: crate::LIQUIDITY_POOL_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateAmmsConfigProvidersFeeRateInstructionData {
            discriminator: [u8; 8],
            }

impl UpdateAmmsConfigProvidersFeeRateInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [202, 201, 73, 47, 40, 32, 173, 196],
                                }
  }
}

impl Default for UpdateAmmsConfigProvidersFeeRateInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateAmmsConfigProvidersFeeRateInstructionArgs {
                  pub new_providers_fee_rate_basis_points: u16,
      }


/// Instruction builder for `UpdateAmmsConfigProvidersFeeRate`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` authority
          ///   1. `[]` amms_configs_manager
                ///   2. `[writable]` amms_config
#[derive(Clone, Debug, Default)]
pub struct UpdateAmmsConfigProvidersFeeRateBuilder {
            authority: Option<solana_program::pubkey::Pubkey>,
                amms_configs_manager: Option<solana_program::pubkey::Pubkey>,
                amms_config: Option<solana_program::pubkey::Pubkey>,
                        new_providers_fee_rate_basis_points: Option<u16>,
        __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl UpdateAmmsConfigProvidersFeeRateBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            #[inline(always)]
    pub fn amms_configs_manager(&mut self, amms_configs_manager: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.amms_configs_manager = Some(amms_configs_manager);
                    self
    }
            #[inline(always)]
    pub fn amms_config(&mut self, amms_config: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.amms_config = Some(amms_config);
                    self
    }
                    #[inline(always)]
      pub fn new_providers_fee_rate_basis_points(&mut self, new_providers_fee_rate_basis_points: u16) -> &mut Self {
        self.new_providers_fee_rate_basis_points = Some(new_providers_fee_rate_basis_points);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_program::instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_program::instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_program::instruction::Instruction {
    let accounts = UpdateAmmsConfigProvidersFeeRate {
                              authority: self.authority.expect("authority is not set"),
                                        amms_configs_manager: self.amms_configs_manager.expect("amms_configs_manager is not set"),
                                        amms_config: self.amms_config.expect("amms_config is not set"),
                      };
          let args = UpdateAmmsConfigProvidersFeeRateInstructionArgs {
                                                              new_providers_fee_rate_basis_points: self.new_providers_fee_rate_basis_points.clone().expect("new_providers_fee_rate_basis_points is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `update_amms_config_providers_fee_rate` CPI accounts.
  pub struct UpdateAmmsConfigProvidersFeeRateCpiAccounts<'a, 'b> {
          
                    
              pub authority: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub amms_configs_manager: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub amms_config: &'b solana_program::account_info::AccountInfo<'a>,
            }

/// `update_amms_config_providers_fee_rate` CPI instruction.
pub struct UpdateAmmsConfigProvidersFeeRateCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_program::account_info::AccountInfo<'a>,
      
              
          pub authority: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub amms_configs_manager: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub amms_config: &'b solana_program::account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: UpdateAmmsConfigProvidersFeeRateInstructionArgs,
  }

impl<'a, 'b> UpdateAmmsConfigProvidersFeeRateCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_program::account_info::AccountInfo<'a>,
          accounts: UpdateAmmsConfigProvidersFeeRateCpiAccounts<'a, 'b>,
              args: UpdateAmmsConfigProvidersFeeRateInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              authority: accounts.authority,
              amms_configs_manager: accounts.amms_configs_manager,
              amms_config: accounts.amms_config,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program::entrypoint::ProgramResult {
    let mut accounts = Vec::with_capacity(3+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            *self.authority.key,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.amms_configs_manager.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.amms_config.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_program::instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = borsh::to_vec(&UpdateAmmsConfigProvidersFeeRateInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&self.__args).unwrap();
      data.append(&mut args);
    
    let instruction = solana_program::instruction::Instruction {
      program_id: crate::LIQUIDITY_POOL_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.authority.clone());
                        account_infos.push(self.amms_configs_manager.clone());
                        account_infos.push(self.amms_config.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_program::program::invoke(&instruction, &account_infos)
    } else {
      solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `UpdateAmmsConfigProvidersFeeRate` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` authority
          ///   1. `[]` amms_configs_manager
                ///   2. `[writable]` amms_config
#[derive(Clone, Debug)]
pub struct UpdateAmmsConfigProvidersFeeRateCpiBuilder<'a, 'b> {
  instruction: Box<UpdateAmmsConfigProvidersFeeRateCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateAmmsConfigProvidersFeeRateCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(UpdateAmmsConfigProvidersFeeRateCpiBuilderInstruction {
      __program: program,
              authority: None,
              amms_configs_manager: None,
              amms_config: None,
                                            new_providers_fee_rate_basis_points: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
      #[inline(always)]
    pub fn amms_configs_manager(&mut self, amms_configs_manager: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.amms_configs_manager = Some(amms_configs_manager);
                    self
    }
      #[inline(always)]
    pub fn amms_config(&mut self, amms_config: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.amms_config = Some(amms_config);
                    self
    }
                    #[inline(always)]
      pub fn new_providers_fee_rate_basis_points(&mut self, new_providers_fee_rate_basis_points: u16) -> &mut Self {
        self.instruction.new_providers_fee_rate_basis_points = Some(new_providers_fee_rate_basis_points);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_program::account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
          let args = UpdateAmmsConfigProvidersFeeRateInstructionArgs {
                                                              new_providers_fee_rate_basis_points: self.instruction.new_providers_fee_rate_basis_points.clone().expect("new_providers_fee_rate_basis_points is not set"),
                                    };
        let instruction = UpdateAmmsConfigProvidersFeeRateCpi {
        __program: self.instruction.__program,
                  
          authority: self.instruction.authority.expect("authority is not set"),
                  
          amms_configs_manager: self.instruction.amms_configs_manager.expect("amms_configs_manager is not set"),
                  
          amms_config: self.instruction.amms_config.expect("amms_config is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct UpdateAmmsConfigProvidersFeeRateCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_program::account_info::AccountInfo<'a>,
            authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                amms_configs_manager: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                amms_config: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                        new_providers_fee_rate_basis_points: Option<u16>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)>,
}

