/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';
import {
  getQ64128Decoder,
  getQ64128Encoder,
  type Q64128,
  type Q64128Args,
} from '.';

export type CloseStakePositionEvent = {
  launchpool: Address;
  signer: Address;
  stakePosition: Address;
  stakedAmount: bigint;
  rewardPerToken: Q64128;
  participantsRewardLeftToDistribute: Q64128;
  participantsRewardLeftToObtain: bigint;
  pending: Q64128;
  stakeReceived: bigint;
  rewardReceived: bigint;
  closeTimestamp: bigint;
};

export type CloseStakePositionEventArgs = {
  launchpool: Address;
  signer: Address;
  stakePosition: Address;
  stakedAmount: number | bigint;
  rewardPerToken: Q64128Args;
  participantsRewardLeftToDistribute: Q64128Args;
  participantsRewardLeftToObtain: number | bigint;
  pending: Q64128Args;
  stakeReceived: number | bigint;
  rewardReceived: number | bigint;
  closeTimestamp: number | bigint;
};

export function getCloseStakePositionEventEncoder(): Encoder<CloseStakePositionEventArgs> {
  return getStructEncoder([
    ['launchpool', getAddressEncoder()],
    ['signer', getAddressEncoder()],
    ['stakePosition', getAddressEncoder()],
    ['stakedAmount', getU64Encoder()],
    ['rewardPerToken', getQ64128Encoder()],
    ['participantsRewardLeftToDistribute', getQ64128Encoder()],
    ['participantsRewardLeftToObtain', getU64Encoder()],
    ['pending', getQ64128Encoder()],
    ['stakeReceived', getU64Encoder()],
    ['rewardReceived', getU64Encoder()],
    ['closeTimestamp', getU64Encoder()],
  ]);
}

export function getCloseStakePositionEventDecoder(): Decoder<CloseStakePositionEvent> {
  return getStructDecoder([
    ['launchpool', getAddressDecoder()],
    ['signer', getAddressDecoder()],
    ['stakePosition', getAddressDecoder()],
    ['stakedAmount', getU64Decoder()],
    ['rewardPerToken', getQ64128Decoder()],
    ['participantsRewardLeftToDistribute', getQ64128Decoder()],
    ['participantsRewardLeftToObtain', getU64Decoder()],
    ['pending', getQ64128Decoder()],
    ['stakeReceived', getU64Decoder()],
    ['rewardReceived', getU64Decoder()],
    ['closeTimestamp', getU64Decoder()],
  ]);
}

export function getCloseStakePositionEventCodec(): Codec<
  CloseStakePositionEventArgs,
  CloseStakePositionEvent
> {
  return combineCodec(
    getCloseStakePositionEventEncoder(),
    getCloseStakePositionEventDecoder()
  );
}
