/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';
import {
  getQ64128Decoder,
  getQ64128Encoder,
  type Q64128,
  type Q64128Args,
} from '.';

export type IncreaseStakePositionEvent = {
  launchpool: Address;
  signer: Address;
  stakePosition: Address;
  stakedAmount: bigint;
  rewardPerToken: Q64128;
  participantsRewardLeftToDistribute: Q64128;
  increaseStakeAmount: bigint;
  pending: Q64128;
  stakeAmount: bigint;
  rewardEarned: Q64128;
  rewardDebt: Q64128;
  increaseStakeTimestamp: bigint;
};

export type IncreaseStakePositionEventArgs = {
  launchpool: Address;
  signer: Address;
  stakePosition: Address;
  stakedAmount: number | bigint;
  rewardPerToken: Q64128Args;
  participantsRewardLeftToDistribute: Q64128Args;
  increaseStakeAmount: number | bigint;
  pending: Q64128Args;
  stakeAmount: number | bigint;
  rewardEarned: Q64128Args;
  rewardDebt: Q64128Args;
  increaseStakeTimestamp: number | bigint;
};

export function getIncreaseStakePositionEventEncoder(): Encoder<IncreaseStakePositionEventArgs> {
  return getStructEncoder([
    ['launchpool', getAddressEncoder()],
    ['signer', getAddressEncoder()],
    ['stakePosition', getAddressEncoder()],
    ['stakedAmount', getU64Encoder()],
    ['rewardPerToken', getQ64128Encoder()],
    ['participantsRewardLeftToDistribute', getQ64128Encoder()],
    ['increaseStakeAmount', getU64Encoder()],
    ['pending', getQ64128Encoder()],
    ['stakeAmount', getU64Encoder()],
    ['rewardEarned', getQ64128Encoder()],
    ['rewardDebt', getQ64128Encoder()],
    ['increaseStakeTimestamp', getU64Encoder()],
  ]);
}

export function getIncreaseStakePositionEventDecoder(): Decoder<IncreaseStakePositionEvent> {
  return getStructDecoder([
    ['launchpool', getAddressDecoder()],
    ['signer', getAddressDecoder()],
    ['stakePosition', getAddressDecoder()],
    ['stakedAmount', getU64Decoder()],
    ['rewardPerToken', getQ64128Decoder()],
    ['participantsRewardLeftToDistribute', getQ64128Decoder()],
    ['increaseStakeAmount', getU64Decoder()],
    ['pending', getQ64128Decoder()],
    ['stakeAmount', getU64Decoder()],
    ['rewardEarned', getQ64128Decoder()],
    ['rewardDebt', getQ64128Decoder()],
    ['increaseStakeTimestamp', getU64Decoder()],
  ]);
}

export function getIncreaseStakePositionEventCodec(): Codec<
  IncreaseStakePositionEventArgs,
  IncreaseStakePositionEvent
> {
  return combineCodec(
    getIncreaseStakePositionEventEncoder(),
    getIncreaseStakePositionEventDecoder()
  );
}
