/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum PositionStatus {
  Uninitialized,
  Initialized,
  Opened,
  Closed,
}

export type PositionStatusArgs = PositionStatus;

export function getPositionStatusEncoder(): Encoder<PositionStatusArgs> {
  return getEnumEncoder(PositionStatus);
}

export function getPositionStatusDecoder(): Decoder<PositionStatus> {
  return getEnumDecoder(PositionStatus);
}

export function getPositionStatusCodec(): Codec<
  PositionStatusArgs,
  PositionStatus
> {
  return combineCodec(getPositionStatusEncoder(), getPositionStatusDecoder());
}
