/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type UpdateLaunchpoolsConfigProtocolRewardShareEvent = {
  authority: Address;
  launchpoolsConfig: Address;
  newProtocolRewardShareBasisPoints: number;
  timestamp: bigint;
};

export type UpdateLaunchpoolsConfigProtocolRewardShareEventArgs = {
  authority: Address;
  launchpoolsConfig: Address;
  newProtocolRewardShareBasisPoints: number;
  timestamp: number | bigint;
};

export function getUpdateLaunchpoolsConfigProtocolRewardShareEventEncoder(): Encoder<UpdateLaunchpoolsConfigProtocolRewardShareEventArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['launchpoolsConfig', getAddressEncoder()],
    ['newProtocolRewardShareBasisPoints', getU16Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getUpdateLaunchpoolsConfigProtocolRewardShareEventDecoder(): Decoder<UpdateLaunchpoolsConfigProtocolRewardShareEvent> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['launchpoolsConfig', getAddressDecoder()],
    ['newProtocolRewardShareBasisPoints', getU16Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getUpdateLaunchpoolsConfigProtocolRewardShareEventCodec(): Codec<
  UpdateLaunchpoolsConfigProtocolRewardShareEventArgs,
  UpdateLaunchpoolsConfigProtocolRewardShareEvent
> {
  return combineCodec(
    getUpdateLaunchpoolsConfigProtocolRewardShareEventEncoder(),
    getUpdateLaunchpoolsConfigProtocolRewardShareEventDecoder()
  );
}
