/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type UpdateLaunchpoolsConfigPositionSizesEvent = {
  authority: Address;
  launchpoolsConfig: Address;
  newMinPositionSize: bigint;
  newMaxPositionSize: bigint;
  timestamp: bigint;
};

export type UpdateLaunchpoolsConfigPositionSizesEventArgs = {
  authority: Address;
  launchpoolsConfig: Address;
  newMinPositionSize: number | bigint;
  newMaxPositionSize: number | bigint;
  timestamp: number | bigint;
};

export function getUpdateLaunchpoolsConfigPositionSizesEventEncoder(): Encoder<UpdateLaunchpoolsConfigPositionSizesEventArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['launchpoolsConfig', getAddressEncoder()],
    ['newMinPositionSize', getU64Encoder()],
    ['newMaxPositionSize', getU64Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getUpdateLaunchpoolsConfigPositionSizesEventDecoder(): Decoder<UpdateLaunchpoolsConfigPositionSizesEvent> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['launchpoolsConfig', getAddressDecoder()],
    ['newMinPositionSize', getU64Decoder()],
    ['newMaxPositionSize', getU64Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getUpdateLaunchpoolsConfigPositionSizesEventCodec(): Codec<
  UpdateLaunchpoolsConfigPositionSizesEventArgs,
  UpdateLaunchpoolsConfigPositionSizesEvent
> {
  return combineCodec(
    getUpdateLaunchpoolsConfigPositionSizesEventEncoder(),
    getUpdateLaunchpoolsConfigPositionSizesEventDecoder()
  );
}
