//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#close_stake_position_event;
  pub(crate) mod r#collect_protocol_reward_event;
  pub(crate) mod r#increase_stake_position_event;
  pub(crate) mod r#initialize_launchpool_event;
  pub(crate) mod r#initialize_launchpools_config_event;
  pub(crate) mod r#initialize_launchpools_configs_manager_event;
  pub(crate) mod r#launch_launchpool_event;
  pub(crate) mod r#launchpool_status;
  pub(crate) mod r#open_stake_position_event;
  pub(crate) mod r#position_status;
  pub(crate) mod r#q64128;
  pub(crate) mod r#u192;
  pub(crate) mod r#update_launchpools_config_duration_event;
  pub(crate) mod r#update_launchpools_config_position_sizes_event;
  pub(crate) mod r#update_launchpools_config_protocol_reward_share_event;
  pub(crate) mod r#update_launchpools_config_reward_authority_event;
  pub(crate) mod r#update_launchpools_configs_manager_authority_event;
  pub(crate) mod r#update_launchpools_configs_manager_head_authority_event;

  pub use self::r#close_stake_position_event::*;
  pub use self::r#collect_protocol_reward_event::*;
  pub use self::r#increase_stake_position_event::*;
  pub use self::r#initialize_launchpool_event::*;
  pub use self::r#initialize_launchpools_config_event::*;
  pub use self::r#initialize_launchpools_configs_manager_event::*;
  pub use self::r#launch_launchpool_event::*;
  pub use self::r#launchpool_status::*;
  pub use self::r#open_stake_position_event::*;
  pub use self::r#position_status::*;
  pub use self::r#q64128::*;
  pub use self::r#u192::*;
  pub use self::r#update_launchpools_config_duration_event::*;
  pub use self::r#update_launchpools_config_position_sizes_event::*;
  pub use self::r#update_launchpools_config_protocol_reward_share_event::*;
  pub use self::r#update_launchpools_config_reward_authority_event::*;
  pub use self::r#update_launchpools_configs_manager_authority_event::*;
  pub use self::r#update_launchpools_configs_manager_head_authority_event::*;

