//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#amms_config;
  pub(crate) mod r#amms_configs_manager;
  pub(crate) mod r#cp_amm;

  pub use self::r#amms_config::*;
  pub use self::r#amms_configs_manager::*;
  pub use self::r#cp_amm::*;

