//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// Accounts.
#[derive(Debug)]
pub struct InitializeAmmsConfig {
      
              
          pub authority: solana_program::pubkey::Pubkey,
          
              
          pub amms_configs_manager: solana_program::pubkey::Pubkey,
          
              
          pub amms_config: solana_program::pubkey::Pubkey,
          
              
          pub fee_authority: solana_program::pubkey::Pubkey,
          
              
          pub rent: solana_program::pubkey::Pubkey,
          
              
          pub system_program: solana_program::pubkey::Pubkey,
      }

impl InitializeAmmsConfig {
  pub fn instruction(&self, args: InitializeAmmsConfigInstructionArgs) -> solana_program::instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: InitializeAmmsConfigInstructionArgs, remaining_accounts: &[solana_program::instruction::AccountMeta]) -> solana_program::instruction::Instruction {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            self.authority,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.amms_configs_manager,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.amms_config,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.fee_authority,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.rent,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = borsh::to_vec(&InitializeAmmsConfigInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&args).unwrap();
      data.append(&mut args);
    
    solana_program::instruction::Instruction {
      program_id: crate::LIQUIDITY_POOL_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct InitializeAmmsConfigInstructionData {
            discriminator: [u8; 8],
                  }

impl InitializeAmmsConfigInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [249, 101, 117, 47, 67, 156, 98, 162],
                                              }
  }
}

impl Default for InitializeAmmsConfigInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct InitializeAmmsConfigInstructionArgs {
                  pub protocol_fee_rate_basis_points: u16,
                pub providers_fee_rate_basis_points: u16,
      }


/// Instruction builder for `InitializeAmmsConfig`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` authority
                ///   1. `[writable]` amms_configs_manager
                ///   2. `[writable]` amms_config
          ///   3. `[]` fee_authority
                ///   4. `[optional]` rent (default to `SysvarRent111111111111111111111111111111111`)
                ///   5. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct InitializeAmmsConfigBuilder {
            authority: Option<solana_program::pubkey::Pubkey>,
                amms_configs_manager: Option<solana_program::pubkey::Pubkey>,
                amms_config: Option<solana_program::pubkey::Pubkey>,
                fee_authority: Option<solana_program::pubkey::Pubkey>,
                rent: Option<solana_program::pubkey::Pubkey>,
                system_program: Option<solana_program::pubkey::Pubkey>,
                        protocol_fee_rate_basis_points: Option<u16>,
                providers_fee_rate_basis_points: Option<u16>,
        __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl InitializeAmmsConfigBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            #[inline(always)]
    pub fn amms_configs_manager(&mut self, amms_configs_manager: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.amms_configs_manager = Some(amms_configs_manager);
                    self
    }
            #[inline(always)]
    pub fn amms_config(&mut self, amms_config: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.amms_config = Some(amms_config);
                    self
    }
            #[inline(always)]
    pub fn fee_authority(&mut self, fee_authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.fee_authority = Some(fee_authority);
                    self
    }
            /// `[optional account, default to 'SysvarRent111111111111111111111111111111111']`
#[inline(always)]
    pub fn rent(&mut self, rent: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.rent = Some(rent);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn protocol_fee_rate_basis_points(&mut self, protocol_fee_rate_basis_points: u16) -> &mut Self {
        self.protocol_fee_rate_basis_points = Some(protocol_fee_rate_basis_points);
        self
      }
                #[inline(always)]
      pub fn providers_fee_rate_basis_points(&mut self, providers_fee_rate_basis_points: u16) -> &mut Self {
        self.providers_fee_rate_basis_points = Some(providers_fee_rate_basis_points);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_program::instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_program::instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_program::instruction::Instruction {
    let accounts = InitializeAmmsConfig {
                              authority: self.authority.expect("authority is not set"),
                                        amms_configs_manager: self.amms_configs_manager.expect("amms_configs_manager is not set"),
                                        amms_config: self.amms_config.expect("amms_config is not set"),
                                        fee_authority: self.fee_authority.expect("fee_authority is not set"),
                                        rent: self.rent.unwrap_or(solana_program::pubkey!("SysvarRent111111111111111111111111111111111")),
                                        system_program: self.system_program.unwrap_or(solana_program::pubkey!("11111111111111111111111111111111")),
                      };
          let args = InitializeAmmsConfigInstructionArgs {
                                                              protocol_fee_rate_basis_points: self.protocol_fee_rate_basis_points.clone().expect("protocol_fee_rate_basis_points is not set"),
                                                                  providers_fee_rate_basis_points: self.providers_fee_rate_basis_points.clone().expect("providers_fee_rate_basis_points is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `initialize_amms_config` CPI accounts.
  pub struct InitializeAmmsConfigCpiAccounts<'a, 'b> {
          
                    
              pub authority: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub amms_configs_manager: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub amms_config: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub fee_authority: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub rent: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_program::account_info::AccountInfo<'a>,
            }

/// `initialize_amms_config` CPI instruction.
pub struct InitializeAmmsConfigCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_program::account_info::AccountInfo<'a>,
      
              
          pub authority: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub amms_configs_manager: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub amms_config: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub fee_authority: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub rent: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_program::account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: InitializeAmmsConfigInstructionArgs,
  }

impl<'a, 'b> InitializeAmmsConfigCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_program::account_info::AccountInfo<'a>,
          accounts: InitializeAmmsConfigCpiAccounts<'a, 'b>,
              args: InitializeAmmsConfigInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              authority: accounts.authority,
              amms_configs_manager: accounts.amms_configs_manager,
              amms_config: accounts.amms_config,
              fee_authority: accounts.fee_authority,
              rent: accounts.rent,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program::entrypoint::ProgramResult {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            *self.authority.key,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.amms_configs_manager.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.amms_config.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.fee_authority.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.rent.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_program::instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = borsh::to_vec(&InitializeAmmsConfigInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&self.__args).unwrap();
      data.append(&mut args);
    
    let instruction = solana_program::instruction::Instruction {
      program_id: crate::LIQUIDITY_POOL_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.authority.clone());
                        account_infos.push(self.amms_configs_manager.clone());
                        account_infos.push(self.amms_config.clone());
                        account_infos.push(self.fee_authority.clone());
                        account_infos.push(self.rent.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_program::program::invoke(&instruction, &account_infos)
    } else {
      solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `InitializeAmmsConfig` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` authority
                ///   1. `[writable]` amms_configs_manager
                ///   2. `[writable]` amms_config
          ///   3. `[]` fee_authority
          ///   4. `[]` rent
          ///   5. `[]` system_program
#[derive(Clone, Debug)]
pub struct InitializeAmmsConfigCpiBuilder<'a, 'b> {
  instruction: Box<InitializeAmmsConfigCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitializeAmmsConfigCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(InitializeAmmsConfigCpiBuilderInstruction {
      __program: program,
              authority: None,
              amms_configs_manager: None,
              amms_config: None,
              fee_authority: None,
              rent: None,
              system_program: None,
                                            protocol_fee_rate_basis_points: None,
                                providers_fee_rate_basis_points: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
      #[inline(always)]
    pub fn amms_configs_manager(&mut self, amms_configs_manager: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.amms_configs_manager = Some(amms_configs_manager);
                    self
    }
      #[inline(always)]
    pub fn amms_config(&mut self, amms_config: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.amms_config = Some(amms_config);
                    self
    }
      #[inline(always)]
    pub fn fee_authority(&mut self, fee_authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_authority = Some(fee_authority);
                    self
    }
      #[inline(always)]
    pub fn rent(&mut self, rent: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.rent = Some(rent);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn protocol_fee_rate_basis_points(&mut self, protocol_fee_rate_basis_points: u16) -> &mut Self {
        self.instruction.protocol_fee_rate_basis_points = Some(protocol_fee_rate_basis_points);
        self
      }
                #[inline(always)]
      pub fn providers_fee_rate_basis_points(&mut self, providers_fee_rate_basis_points: u16) -> &mut Self {
        self.instruction.providers_fee_rate_basis_points = Some(providers_fee_rate_basis_points);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_program::account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
          let args = InitializeAmmsConfigInstructionArgs {
                                                              protocol_fee_rate_basis_points: self.instruction.protocol_fee_rate_basis_points.clone().expect("protocol_fee_rate_basis_points is not set"),
                                                                  providers_fee_rate_basis_points: self.instruction.providers_fee_rate_basis_points.clone().expect("providers_fee_rate_basis_points is not set"),
                                    };
        let instruction = InitializeAmmsConfigCpi {
        __program: self.instruction.__program,
                  
          authority: self.instruction.authority.expect("authority is not set"),
                  
          amms_configs_manager: self.instruction.amms_configs_manager.expect("amms_configs_manager is not set"),
                  
          amms_config: self.instruction.amms_config.expect("amms_config is not set"),
                  
          fee_authority: self.instruction.fee_authority.expect("fee_authority is not set"),
                  
          rent: self.instruction.rent.expect("rent is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct InitializeAmmsConfigCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_program::account_info::AccountInfo<'a>,
            authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                amms_configs_manager: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                amms_config: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                fee_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                rent: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                        protocol_fee_rate_basis_points: Option<u16>,
                providers_fee_rate_basis_points: Option<u16>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)>,
}

