//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_program::{pubkey, pubkey::Pubkey};


  /// `launchpool` program ID.
  pub const LAUNCHPOOL_ID: Pubkey = pubkey!("5M9TeHHBeAtUd956yRUW9TEULF5XqGUdcyfy74YDzXHU");

