//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#close_stake_position;
  pub(crate) mod r#collect_protocol_reward;
  pub(crate) mod r#increase_stake_position;
  pub(crate) mod r#initialize_launchpool;
  pub(crate) mod r#initialize_launchpools_config;
  pub(crate) mod r#initialize_launchpools_configs_manager;
  pub(crate) mod r#launch_launchpool;
  pub(crate) mod r#open_stake_position;
  pub(crate) mod r#update_launchpools_config_duration;
  pub(crate) mod r#update_launchpools_config_position_sizes;
  pub(crate) mod r#update_launchpools_config_protocol_reward_share;
  pub(crate) mod r#update_launchpools_config_reward_authority;
  pub(crate) mod r#update_launchpools_configs_manager_authority;
  pub(crate) mod r#update_launchpools_configs_manager_head_authority;

  pub use self::r#close_stake_position::*;
  pub use self::r#collect_protocol_reward::*;
  pub use self::r#increase_stake_position::*;
  pub use self::r#initialize_launchpool::*;
  pub use self::r#initialize_launchpools_config::*;
  pub use self::r#initialize_launchpools_configs_manager::*;
  pub use self::r#launch_launchpool::*;
  pub use self::r#open_stake_position::*;
  pub use self::r#update_launchpools_config_duration::*;
  pub use self::r#update_launchpools_config_position_sizes::*;
  pub use self::r#update_launchpools_config_protocol_reward_share::*;
  pub use self::r#update_launchpools_config_reward_authority::*;
  pub use self::r#update_launchpools_configs_manager_authority::*;
  pub use self::r#update_launchpools_configs_manager_head_authority::*;

