//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// Accounts.
#[derive(Debug)]
pub struct UpdateLaunchpoolsConfigPositionSizes {
      
              
          pub authority: solana_program::pubkey::Pubkey,
          
              
          pub launchpools_configs_manager: solana_program::pubkey::Pubkey,
          
              
          pub launchpools_config: solana_program::pubkey::Pubkey,
      }

impl UpdateLaunchpoolsConfigPositionSizes {
  pub fn instruction(&self, args: UpdateLaunchpoolsConfigPositionSizesInstructionArgs) -> solana_program::instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: UpdateLaunchpoolsConfigPositionSizesInstructionArgs, remaining_accounts: &[solana_program::instruction::AccountMeta]) -> solana_program::instruction::Instruction {
    let mut accounts = Vec::with_capacity(3+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            self.authority,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.launchpools_configs_manager,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.launchpools_config,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = borsh::to_vec(&UpdateLaunchpoolsConfigPositionSizesInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&args).unwrap();
      data.append(&mut args);
    
    solana_program::instruction::Instruction {
      program_id: crate::LAUNCHPOOL_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateLaunchpoolsConfigPositionSizesInstructionData {
            discriminator: [u8; 8],
                  }

impl UpdateLaunchpoolsConfigPositionSizesInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [216, 176, 23, 53, 154, 201, 212, 172],
                                              }
  }
}

impl Default for UpdateLaunchpoolsConfigPositionSizesInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateLaunchpoolsConfigPositionSizesInstructionArgs {
                  pub new_min_position_size: u64,
                pub new_max_position_size: u64,
      }


/// Instruction builder for `UpdateLaunchpoolsConfigPositionSizes`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` authority
          ///   1. `[]` launchpools_configs_manager
                ///   2. `[writable]` launchpools_config
#[derive(Clone, Debug, Default)]
pub struct UpdateLaunchpoolsConfigPositionSizesBuilder {
            authority: Option<solana_program::pubkey::Pubkey>,
                launchpools_configs_manager: Option<solana_program::pubkey::Pubkey>,
                launchpools_config: Option<solana_program::pubkey::Pubkey>,
                        new_min_position_size: Option<u64>,
                new_max_position_size: Option<u64>,
        __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl UpdateLaunchpoolsConfigPositionSizesBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            #[inline(always)]
    pub fn launchpools_configs_manager(&mut self, launchpools_configs_manager: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.launchpools_configs_manager = Some(launchpools_configs_manager);
                    self
    }
            #[inline(always)]
    pub fn launchpools_config(&mut self, launchpools_config: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.launchpools_config = Some(launchpools_config);
                    self
    }
                    #[inline(always)]
      pub fn new_min_position_size(&mut self, new_min_position_size: u64) -> &mut Self {
        self.new_min_position_size = Some(new_min_position_size);
        self
      }
                #[inline(always)]
      pub fn new_max_position_size(&mut self, new_max_position_size: u64) -> &mut Self {
        self.new_max_position_size = Some(new_max_position_size);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_program::instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_program::instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_program::instruction::Instruction {
    let accounts = UpdateLaunchpoolsConfigPositionSizes {
                              authority: self.authority.expect("authority is not set"),
                                        launchpools_configs_manager: self.launchpools_configs_manager.expect("launchpools_configs_manager is not set"),
                                        launchpools_config: self.launchpools_config.expect("launchpools_config is not set"),
                      };
          let args = UpdateLaunchpoolsConfigPositionSizesInstructionArgs {
                                                              new_min_position_size: self.new_min_position_size.clone().expect("new_min_position_size is not set"),
                                                                  new_max_position_size: self.new_max_position_size.clone().expect("new_max_position_size is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `update_launchpools_config_position_sizes` CPI accounts.
  pub struct UpdateLaunchpoolsConfigPositionSizesCpiAccounts<'a, 'b> {
          
                    
              pub authority: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub launchpools_configs_manager: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub launchpools_config: &'b solana_program::account_info::AccountInfo<'a>,
            }

/// `update_launchpools_config_position_sizes` CPI instruction.
pub struct UpdateLaunchpoolsConfigPositionSizesCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_program::account_info::AccountInfo<'a>,
      
              
          pub authority: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub launchpools_configs_manager: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub launchpools_config: &'b solana_program::account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: UpdateLaunchpoolsConfigPositionSizesInstructionArgs,
  }

impl<'a, 'b> UpdateLaunchpoolsConfigPositionSizesCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_program::account_info::AccountInfo<'a>,
          accounts: UpdateLaunchpoolsConfigPositionSizesCpiAccounts<'a, 'b>,
              args: UpdateLaunchpoolsConfigPositionSizesInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              authority: accounts.authority,
              launchpools_configs_manager: accounts.launchpools_configs_manager,
              launchpools_config: accounts.launchpools_config,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program::entrypoint::ProgramResult {
    let mut accounts = Vec::with_capacity(3+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            *self.authority.key,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.launchpools_configs_manager.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.launchpools_config.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_program::instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = borsh::to_vec(&UpdateLaunchpoolsConfigPositionSizesInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&self.__args).unwrap();
      data.append(&mut args);
    
    let instruction = solana_program::instruction::Instruction {
      program_id: crate::LAUNCHPOOL_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.authority.clone());
                        account_infos.push(self.launchpools_configs_manager.clone());
                        account_infos.push(self.launchpools_config.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_program::program::invoke(&instruction, &account_infos)
    } else {
      solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `UpdateLaunchpoolsConfigPositionSizes` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` authority
          ///   1. `[]` launchpools_configs_manager
                ///   2. `[writable]` launchpools_config
#[derive(Clone, Debug)]
pub struct UpdateLaunchpoolsConfigPositionSizesCpiBuilder<'a, 'b> {
  instruction: Box<UpdateLaunchpoolsConfigPositionSizesCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateLaunchpoolsConfigPositionSizesCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(UpdateLaunchpoolsConfigPositionSizesCpiBuilderInstruction {
      __program: program,
              authority: None,
              launchpools_configs_manager: None,
              launchpools_config: None,
                                            new_min_position_size: None,
                                new_max_position_size: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
      #[inline(always)]
    pub fn launchpools_configs_manager(&mut self, launchpools_configs_manager: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.launchpools_configs_manager = Some(launchpools_configs_manager);
                    self
    }
      #[inline(always)]
    pub fn launchpools_config(&mut self, launchpools_config: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.launchpools_config = Some(launchpools_config);
                    self
    }
                    #[inline(always)]
      pub fn new_min_position_size(&mut self, new_min_position_size: u64) -> &mut Self {
        self.instruction.new_min_position_size = Some(new_min_position_size);
        self
      }
                #[inline(always)]
      pub fn new_max_position_size(&mut self, new_max_position_size: u64) -> &mut Self {
        self.instruction.new_max_position_size = Some(new_max_position_size);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_program::account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
          let args = UpdateLaunchpoolsConfigPositionSizesInstructionArgs {
                                                              new_min_position_size: self.instruction.new_min_position_size.clone().expect("new_min_position_size is not set"),
                                                                  new_max_position_size: self.instruction.new_max_position_size.clone().expect("new_max_position_size is not set"),
                                    };
        let instruction = UpdateLaunchpoolsConfigPositionSizesCpi {
        __program: self.instruction.__program,
                  
          authority: self.instruction.authority.expect("authority is not set"),
                  
          launchpools_configs_manager: self.instruction.launchpools_configs_manager.expect("launchpools_configs_manager is not set"),
                  
          launchpools_config: self.instruction.launchpools_config.expect("launchpools_config is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct UpdateLaunchpoolsConfigPositionSizesCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_program::account_info::AccountInfo<'a>,
            authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                launchpools_configs_manager: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                launchpools_config: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                        new_min_position_size: Option<u64>,
                new_max_position_size: Option<u64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)>,
}

