//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_program::{pubkey, pubkey::Pubkey};


  /// `liquidity_pool` program ID.
  pub const LIQUIDITY_POOL_ID: Pubkey = pubkey!("2M2QKXZuuERizynTpUwfD7FkdhKHWAFVKiCFGBSxXr3X");

