//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_program::pubkey::Pubkey;
use crate::generated::types::Q64128;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SwapInCpAmmEvent {
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub swapper: Pubkey,
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub cp_amm: Pubkey,
pub is_in_out: bool,
pub swapped_amount: u64,
pub received_amount: u64,
pub estimated_result: u64,
pub allowed_slippage: u64,
pub base_liquidity: u64,
pub quote_liquidity: u64,
pub protocol_base_fees_to_redeem: u64,
pub protocol_quote_fees_to_redeem: u64,
pub constant_product_sqrt: Q64128,
pub base_quote_ratio_sqrt: Q64128,
pub timestamp: i64,
}


